### ISSUE TITLE
Task model in database

### ISSUE THREAD

**Issue by pepyta** [pepyta/sygnmnt#18]
Task model:
```
id String @id() @default(uuid())
name String
description String
team Team

teamid String
```

**Comment by 2976579765** [comment]
This should also store whether testing is automated and if so, what needs to be ran, etc.

**Comment by pepyta** [comment]
We can say that a task is automated if it has test-files uploaded by the teacher, but those are not included in this issue. However, they are present in the source code, so it's not a big issue.
