### ISSUE TITLE
Team model in database

### ISSUE THREAD

**Issue by pepyta** [pepyta/sygnmnt#7]
Team model
```
id       String @default(uuid()) @id
name String
```

Role: `OWNER` / `MEMBER`

As a user can have multiple teams and a team can have multiple member, this is an N-M connection, which should be stored in a separate table.

Membership
```
user     User 
team    Team
role      Role

userid  String
teamid String
@@id([userid, teamid])
```

**Comment by 2976579765** [comment]
There should be a third role for members which have higher privileges, but do not own the group. Only the owner would be able to manage permissions of their groups' members and the third (let's call them `AUXILIARY` for now) could do everything except for changing roles.
